import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { MyThemeProvider } from "@/theme/MyThemeProvider";
import { ThemeOptionsProvider } from "@/theme/ThemeOptionsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeOptionsProvider>
          <MyThemeProvider>{children}</MyThemeProvider>
        </ThemeOptionsProvider>
      </body>
    </html>
  );
}
