import { MyThemeProvider } from "@/theme/MyThemeProvider";
import { ThemeOptionsProvider } from "@/theme/ThemeOptionsContext";
import type { Metadata } from "next";
import "./globals.css";
import { MyQueryClientProvider } from "@/provider/MyQueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyQueryClientProvider>
          <ThemeOptionsProvider>
            <MyThemeProvider>{children}</MyThemeProvider>
          </ThemeOptionsProvider>
        </MyQueryClientProvider>
      </body>
    </html>
  );
}
